// Generated by Wrangler by running `wrangler types`

export interface Env {
  D1: D1Database;
  AUTH_ITERATIONS?: string;
  AUTH_HASH?: "SHA512" | "SHA384" | "SHA256";
  AUTH_KDF?: "pbkdf2" | "scrypt";
}
